<package format="3">
  <name>tmc_realtime_tools</name>
  <version>3.0.0</version>
  <description>The reusable tools for realtime loop.</description>

  <maintainer email="xr-hsr-support@mail.toyota.co.jp">HSR Support</maintainer>
  <license>BSD 3-clause Clear License</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>

  <test_depend>ament_cmake_gtest</test_depend>
  <test_depend>std_msgs</test_depend>

  <export>
  </export>
</package>