<package format="3">
  <name>tmc_realtime_controllers</name>
  <version>2.1.0</version>
  <description>The robot independent controllers.</description>

  <maintainer email="xr-hsr-support@mail.toyota.co.jp">HSR Support</maintainer>
  <license>BSD 3-clause Clear License</license>
  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>controller_interface</depend>
  <depend>lifecycle_msgs</depend>
  <depend>pluginlib</depend>
  <depend>realtime_tools</depend>
  <depend>std_msgs</depend>
  <depend>tmc_control_msgs</depend>
  <depend>tmc_exxx_servo_motor_protocol</depend>
  <depend>tmc_utils</depend>

  <test_depend>ament_cmake_gtest</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>